// Generated by scripts/build-manifest.mjs — do not edit by hand.
// Metadata for Template mode in the HTML generator. Rebuild: npm run build.
(typeof window !== 'undefined' ? window : globalThis).LADDER_TEMPLATES = [
 {
  "id": "cage-fhl",
  "name": "Cat Ladder with Safety Cage",
  "kind": "l1",
  "base": {
   "svg": "base.clean.svg",
   "width": 1122.5601,
   "height": 793.76001
  },
  "params": [
   {
    "id": "customer",
    "label": "Customer",
    "type": "text",
    "default": "FHL CONSTRUCTION SDN BHD"
   },
   {
    "id": "drawingNo",
    "label": "Drawing No.",
    "type": "text",
    "default": "LSB/2607/004/FHL/R00"
   },
   {
    "id": "workingLoad",
    "label": "Working load",
    "type": "text",
    "default": "150KG"
   },
   {
    "id": "productName",
    "label": "Title",
    "type": "text",
    "default": "ALUMINIUM CAT LADDER BODY,HANDRAIL & CAGE RING TYPE"
   },
   {
    "id": "topWidth",
    "label": "Top width",
    "type": "text",
    "default": "500.00"
   },
   {
    "id": "ladderWidth",
    "label": "Ladder width",
    "type": "text",
    "default": "450.00"
   },
   {
    "id": "cageHeight",
    "label": "Cage height",
    "type": "text",
    "default": "5360.40",
    "formula": "(floorToLanding * 0.8060751879699247).toFixed(2)"
   },
   {
    "id": "floorToLanding",
    "label": "Floor to landing",
    "type": "text",
    "default": "6650.00"
   },
   {
    "id": "cageStart",
    "label": "Cage start from floor",
    "type": "text",
    "default": "2053.60",
    "formula": "(floorToLanding * 0.308812030075188).toFixed(2)"
   },
   {
    "id": "bottomRung",
    "label": "Bottom rung clearance",
    "type": "text",
    "default": "146.00"
   }
  ],
  "bindings": [
   {
    "value": "FHL CONSTRUCTION SDN BHD",
    "param": "customer",
    "mode": "text"
   },
   {
    "value": "LSB/2607/004/FHL/R00",
    "param": "drawingNo",
    "mode": "text"
   },
   {
    "value": "150KG",
    "param": "workingLoad",
    "mode": "text"
   },
   {
    "value": "ALUMINIUM CAT LADDER BODY,HANDRAIL & CAGE RING TYPE",
    "param": "productName",
    "mode": "text"
   },
   {
    "value": "500.00",
    "param": "topWidth",
    "mode": "group"
   },
   {
    "value": "450.00",
    "param": "ladderWidth",
    "mode": "group"
   },
   {
    "value": "5360.40",
    "param": "cageHeight",
    "mode": "group"
   },
   {
    "value": "6650.00",
    "param": "floorToLanding",
    "mode": "group"
   },
   {
    "value": "2053.60",
    "param": "cageStart",
    "mode": "group"
   },
   {
    "value": "146.00",
    "param": "bottomRung",
    "mode": "group"
   }
  ],
  "sample": {
   "customer": "ACME TOWER CRANES SDN BHD",
   "drawingNo": "LSB/2607/777/ACME/R02",
   "workingLoad": "200KG",
   "productName": "ALUMINIUM CAT LADDER BODY,HANDRAIL & CAGE RING TYPE B",
   "topWidth": "600.00",
   "ladderWidth": "500.00",
   "cageHeight": "5800.00",
   "floorToLanding": "7000.00",
   "cageStart": "2200.00",
   "bottomRung": "160.00"
  }
 },
 {
  "id": "lsb-2607-003-rhc-r00",
  "name": "ALUMINIUM SAFETY LADDER TROLLEY 9 STEP (CUSTOMIZED)",
  "kind": "l1",
  "base": {
   "svg": "base.clean.svg"
  },
  "params": [
   {
    "id": "drawingNo",
    "label": "Drawing No.",
    "type": "text",
    "default": "LSB-2607-003-RHC-R00"
   },
   {
    "id": "customer",
    "label": "Customer",
    "type": "text",
    "default": "RAHABCO ENGINEERING & CONSTRUCTION SDN BHD"
   },
   {
    "id": "workingLoad",
    "label": "Working Load",
    "type": "text",
    "default": "150KG"
   },
   {
    "id": "productName",
    "label": "Title",
    "type": "text",
    "default": "ALUMINIUM SAFETY LADDER TROLLEY 9 STEP (CUSTOMIZED)"
   },
   {
    "id": "dim1",
    "label": "Dimension 1",
    "type": "text",
    "default": "980"
   },
   {
    "id": "dim2",
    "label": "Dimension 2",
    "type": "text",
    "default": "2372"
   },
   {
    "id": "dim3",
    "label": "Dimension 3",
    "type": "text",
    "default": "700"
   },
   {
    "id": "dim4",
    "label": "Dimension 4",
    "type": "text",
    "default": "2500"
   },
   {
    "id": "dim5",
    "label": "Dimension 5",
    "type": "text",
    "default": "1000"
   },
   {
    "id": "dim6",
    "label": "Dimension 6",
    "type": "text",
    "default": "305"
   },
   {
    "id": "dim7",
    "label": "Dimension 7",
    "type": "text",
    "default": "103"
   }
  ],
  "bindings": [
   {
    "value": "LSB-2607-003-RHC-R00",
    "param": "drawingNo",
    "mode": "text"
   },
   {
    "value": "RAHABCO ENGINEERING & CONSTRUCTION SDN BHD",
    "param": "customer",
    "mode": "text"
   },
   {
    "value": "150KG",
    "param": "workingLoad",
    "mode": "text"
   },
   {
    "value": "ALUMINIUM SAFETY LADDER TROLLEY 9 STEP (CUSTOMIZED)",
    "param": "productName",
    "mode": "text"
   },
   {
    "value": "980",
    "param": "dim1",
    "mode": "group"
   },
   {
    "value": "2372",
    "param": "dim2",
    "mode": "group"
   },
   {
    "value": "700",
    "param": "dim3",
    "mode": "group"
   },
   {
    "value": "2500",
    "param": "dim4",
    "mode": "group"
   },
   {
    "value": "1000",
    "param": "dim5",
    "mode": "group"
   },
   {
    "value": "305",
    "param": "dim6",
    "mode": "group"
   },
   {
    "value": "103",
    "param": "dim7",
    "mode": "group"
   },
   {
    "ids": [
     "path1445"
    ],
    "param": "dim1",
    "geom": {
     "op": "stretchX",
     "anchor": 980
    }
   },
   {
    "ids": [
     "path1444"
    ],
    "param": "dim1",
    "geom": {
     "op": "shiftX",
     "anchor": 980,
     "pxPerUnit": 0.0992
    }
   },
   {
    "ids": [
     "text1447",
     "text1448",
     "text1449"
    ],
    "param": "dim1",
    "geom": {
     "op": "shiftX",
     "anchor": 980,
     "pxPerUnit": 0.0496
    }
   },
   {
    "ids": [
     "path1479"
    ],
    "param": "dim2",
    "geom": {
     "op": "stretchX",
     "anchor": 2372
    }
   },
   {
    "ids": [
     "path1478"
    ],
    "param": "dim2",
    "geom": {
     "op": "shiftX",
     "anchor": 2372,
     "pxPerUnit": 0.10840767284991568
    }
   },
   {
    "ids": [
     "text1481",
     "text1482",
     "text1483",
     "text1484"
    ],
    "param": "dim2",
    "geom": {
     "op": "shiftX",
     "anchor": 2372,
     "pxPerUnit": 0.05420383642495784
    }
   },
   {
    "ids": [
     "path1462"
    ],
    "param": "dim3",
    "geom": {
     "op": "stretchX",
     "anchor": 700
    }
   },
   {
    "ids": [
     "path1461"
    ],
    "param": "dim3",
    "geom": {
     "op": "shiftX",
     "anchor": 700,
     "pxPerUnit": 0.09291999999999999
    }
   },
   {
    "ids": [
     "text1464",
     "text1465",
     "text1466"
    ],
    "param": "dim3",
    "geom": {
     "op": "shiftX",
     "anchor": 700,
     "pxPerUnit": 0.046459999999999994
    }
   },
   {
    "ids": [
     "path1436"
    ],
    "param": "dim4",
    "geom": {
     "op": "stretchY",
     "anchor": 2500
    }
   },
   {
    "ids": [
     "path1435"
    ],
    "param": "dim4",
    "geom": {
     "op": "shiftY",
     "anchor": 2500,
     "pxPerUnit": 0.10347840000000001
    }
   },
   {
    "ids": [
     "text1438",
     "text1439",
     "text1440",
     "text1441"
    ],
    "param": "dim4",
    "geom": {
     "op": "shiftY",
     "anchor": 2500,
     "pxPerUnit": 0.051739200000000006
    }
   },
   {
    "ids": [
     "path1453"
    ],
    "param": "dim5",
    "geom": {
     "op": "stretchY",
     "anchor": 1000
    }
   },
   {
    "ids": [
     "path1452"
    ],
    "param": "dim5",
    "geom": {
     "op": "shiftY",
     "anchor": 1000,
     "pxPerUnit": 0.0947227
    }
   },
   {
    "ids": [
     "text1455",
     "text1456",
     "text1457",
     "text1458"
    ],
    "param": "dim5",
    "geom": {
     "op": "shiftY",
     "anchor": 1000,
     "pxPerUnit": 0.04736135
    }
   },
   {
    "ids": [
     "path1429"
    ],
    "param": "dim6",
    "geom": {
     "op": "stretchY",
     "anchor": 305
    }
   },
   {
    "ids": [
     "path1428"
    ],
    "param": "dim6",
    "geom": {
     "op": "shiftY",
     "anchor": 305,
     "pxPerUnit": 0.06141213114754098
    }
   },
   {
    "ids": [
     "text1430",
     "text1431",
     "text1432"
    ],
    "param": "dim6",
    "geom": {
     "op": "shiftY",
     "anchor": 305,
     "pxPerUnit": 0.03070606557377049
    }
   }
  ],
  "sample": {
   "drawingNo": "LSB-2607-003-RHC-R99",
   "customer": "ACME TOWER CRANES SDN BHD",
   "workingLoad": "200KG",
   "productName": "ALUMINIUM SAFETY LADDER TROLLEY 9 STEP (CUSTOMIZED) - REV B",
   "dim1": "1078",
   "dim2": "2609",
   "dim3": "770",
   "dim4": "2750",
   "dim5": "1100",
   "dim6": "336",
   "dim7": "113"
  }
 },
 {
  "id": "lsb-2607-004-fhl-r00",
  "name": "ALUMINIUM CAT LADDER BODY,HANDRAIL & CAGE RING TYPE",
  "kind": "l1",
  "base": {
   "svg": "base.clean.svg"
  },
  "params": [
   {
    "id": "drawingNo",
    "label": "Drawing No.",
    "type": "text",
    "default": "LSB/2607/004/FHL/R00"
   },
   {
    "id": "customer",
    "label": "Customer",
    "type": "text",
    "default": "FHL CONSTRUCTION SDN BHD"
   },
   {
    "id": "workingLoad",
    "label": "Working Load",
    "type": "text",
    "default": "150KG"
   },
   {
    "id": "productName",
    "label": "Title",
    "type": "text",
    "default": "ALUMINIUM CAT LADDER BODY,HANDRAIL & CAGE RING TYPE"
   },
   {
    "id": "dim1",
    "label": "Dimension 1",
    "type": "text",
    "default": "500.00"
   },
   {
    "id": "dim2",
    "label": "Dimension 2",
    "type": "text",
    "default": "6650.00"
   },
   {
    "id": "dim3",
    "label": "Dimension 3",
    "type": "text",
    "default": "900.00"
   },
   {
    "id": "dim4",
    "label": "Dimension 4",
    "type": "text",
    "default": "146.00"
   },
   {
    "id": "dim5",
    "label": "Dimension 5",
    "type": "text",
    "default": "2053.60",
    "formula": "(dim6 * 0.383104).toFixed(2)"
   },
   {
    "id": "dim6",
    "label": "Dimension 6",
    "type": "text",
    "default": "5360.40",
    "formula": "(dim2 * 0.806075).toFixed(2)"
   }
  ],
  "bindings": [
   {
    "value": "LSB/2607/004/FHL/R00",
    "param": "drawingNo",
    "mode": "text"
   },
   {
    "value": "FHL CONSTRUCTION SDN BHD",
    "param": "customer",
    "mode": "text"
   },
   {
    "value": "150KG",
    "param": "workingLoad",
    "mode": "text"
   },
   {
    "value": "ALUMINIUM CAT LADDER BODY,HANDRAIL & CAGE RING TYPE",
    "param": "productName",
    "mode": "text"
   },
   {
    "value": "500.00",
    "param": "dim1",
    "mode": "group"
   },
   {
    "value": "6650.00",
    "param": "dim2",
    "mode": "group"
   },
   {
    "value": "900.00",
    "param": "dim3",
    "mode": "group"
   },
   {
    "value": "146.00",
    "param": "dim4",
    "mode": "group"
   },
   {
    "value": "2053.60",
    "param": "dim5",
    "mode": "group"
   },
   {
    "value": "5360.40",
    "param": "dim6",
    "mode": "group"
   },
   {
    "ids": [
     "path1463"
    ],
    "param": "dim1",
    "geom": {
     "op": "stretchX",
     "anchor": 500
    }
   },
   {
    "ids": [
     "path1462"
    ],
    "param": "dim1",
    "geom": {
     "op": "shiftX",
     "anchor": 500,
     "pxPerUnit": 0.0799946
    }
   },
   {
    "ids": [
     "text1465",
     "text1466",
     "text1467",
     "text1468",
     "text1469",
     "text1470"
    ],
    "param": "dim1",
    "geom": {
     "op": "shiftX",
     "anchor": 500,
     "pxPerUnit": 0.0399973
    }
   },
   {
    "ids": [
     "path1438"
    ],
    "param": "dim2",
    "geom": {
     "op": "stretchY",
     "anchor": 6650
    }
   },
   {
    "ids": [
     "path1437"
    ],
    "param": "dim2",
    "geom": {
     "op": "shiftY",
     "anchor": 6650,
     "pxPerUnit": 0.10345969924812029
    }
   },
   {
    "ids": [
     "text1440",
     "text1441",
     "text1442",
     "text1443",
     "text1444",
     "text1445",
     "text1446"
    ],
    "param": "dim2",
    "geom": {
     "op": "shiftY",
     "anchor": 6650,
     "pxPerUnit": 0.051729849624060145
    }
   },
   {
    "ids": [
     "path1427"
    ],
    "param": "dim3",
    "geom": {
     "op": "stretchY",
     "anchor": 900
    }
   },
   {
    "ids": [
     "path1426"
    ],
    "param": "dim3",
    "geom": {
     "op": "shiftY",
     "anchor": 900,
     "pxPerUnit": 0.08867111111111112
    }
   },
   {
    "ids": [
     "text1429",
     "text1430",
     "text1431",
     "text1432",
     "text1433",
     "text1434"
    ],
    "param": "dim3",
    "geom": {
     "op": "shiftY",
     "anchor": 900,
     "pxPerUnit": 0.04433555555555556
    }
   },
   {
    "ids": [
     "path1452"
    ],
    "param": "dim4",
    "geom": {
     "op": "stretchY",
     "anchor": 146
    }
   },
   {
    "ids": [
     "text1459"
    ],
    "param": "dim4",
    "geom": {
     "op": "shiftY",
     "anchor": 146,
     "pxPerUnit": 0.38375342465753426
    }
   },
   {
    "ids": [
     "text1454",
     "text1455",
     "text1456",
     "text1457",
     "text1458",
     "text1459"
    ],
    "param": "dim4",
    "geom": {
     "op": "shiftY",
     "anchor": 146,
     "pxPerUnit": 0.19187671232876713
    }
   },
   {
    "ids": [
     "path1485"
    ],
    "param": "dim5",
    "geom": {
     "op": "stretchY",
     "anchor": 2053.6
    }
   },
   {
    "ids": [
     "path1484"
    ],
    "param": "dim5",
    "geom": {
     "op": "shiftY",
     "anchor": 2053.6,
     "pxPerUnit": 0.09827814569536425
    }
   },
   {
    "ids": [
     "text1487",
     "text1488",
     "text1489",
     "text1490",
     "text1491",
     "text1492",
     "text1493"
    ],
    "param": "dim5",
    "geom": {
     "op": "shiftY",
     "anchor": 2053.6,
     "pxPerUnit": 0.049139072847682125
    }
   },
   {
    "ids": [
     "path1497"
    ],
    "param": "dim6",
    "geom": {
     "op": "stretchY",
     "anchor": 5360.4
    }
   },
   {
    "ids": [
     "path1496"
    ],
    "param": "dim6",
    "geom": {
     "op": "shiftY",
     "anchor": 5360.4,
     "pxPerUnit": 0.10290295500335797
    }
   },
   {
    "ids": [
     "text1499",
     "text1500",
     "text1501",
     "text1502",
     "text1503",
     "text1504",
     "text1505"
    ],
    "param": "dim6",
    "geom": {
     "op": "shiftY",
     "anchor": 5360.4,
     "pxPerUnit": 0.051451477501678985
    }
   }
  ],
  "sample": {
   "drawingNo": "LSB/2607/004/FHL/R99",
   "customer": "ACME TOWER CRANES SDN BHD",
   "workingLoad": "200KG",
   "productName": "ALUMINIUM CAT LADDER BODY,HANDRAIL & CAGE RING TYPE - REV B",
   "dim1": "550.00",
   "dim2": "7315.00",
   "dim3": "990.00",
   "dim4": "160.60",
   "dim5": "2258.96",
   "dim6": "5896.44"
  }
 },
 {
  "id": "trolley-slt",
  "name": "Safety Ladder Trolley (SLT)",
  "kind": "l1",
  "base": {
   "svg": "base.clean.svg",
   "width": 1122.5601,
   "height": 793.76001
  },
  "params": [
   {
    "id": "customer",
    "label": "Customer",
    "type": "text",
    "default": "RAHABCO ENGINEERING & CONSTRUCTION SDN BHD"
   },
   {
    "id": "drawingNo",
    "label": "Drawing No.",
    "type": "text",
    "default": "LSB-2607-003-RHC-R00"
   },
   {
    "id": "overallHeight",
    "label": "Height",
    "type": "text",
    "default": "3,500 MM"
   },
   {
    "id": "workingLoad",
    "label": "Working load",
    "type": "text",
    "default": "150KG"
   },
   {
    "id": "footprint",
    "label": "Overall footprint",
    "type": "text",
    "default": "2372"
   },
   {
    "id": "productName",
    "label": "Product",
    "type": "text",
    "default": "ALUMINIUM SAFETY LADDER TROLLEY 9 STEP (CUSTOMIZED)"
   }
  ],
  "bindings": [
   {
    "value": "RAHABCO ENGINEERING & CONSTRUCTION SDN BHD",
    "param": "customer",
    "mode": "text"
   },
   {
    "value": "LSB-2607-003-RHC-R00",
    "param": "drawingNo",
    "mode": "text"
   },
   {
    "value": "3,500 MM",
    "param": "overallHeight",
    "mode": "text"
   },
   {
    "value": "150KG",
    "param": "workingLoad",
    "mode": "text"
   },
   {
    "value": "ALUMINIUM SAFETY LADDER TROLLEY 9 STEP (CUSTOMIZED)",
    "param": "productName",
    "mode": "text"
   },
   {
    "value": "2372",
    "param": "footprint",
    "mode": "group"
   },
   {
    "ids": [
     "path1479"
    ],
    "param": "footprint",
    "geom": {
     "op": "stretchX",
     "anchor": 2372
    }
   },
   {
    "ids": [
     "path1478"
    ],
    "param": "footprint",
    "geom": {
     "op": "shiftX",
     "anchor": 2372,
     "pxPerUnit": 0.10821
    }
   },
   {
    "ids": [
     "text1481",
     "text1482",
     "text1483",
     "text1484"
    ],
    "param": "footprint",
    "geom": {
     "op": "shiftX",
     "anchor": 2372,
     "pxPerUnit": 0.054104
    }
   }
  ],
  "sample": {
   "customer": "ACME TOWER CRANES SDN BHD",
   "drawingNo": "LSB-2607-999/ACME/R03",
   "overallHeight": "4,200 MM",
   "workingLoad": "200KG",
   "footprint": "3200",
   "productName": "ALUMINIUM SAFETY LADDER TROLLEY 12 STEP (CUSTOMIZED)"
  }
 }
];
