#!/usr/bin/env node
// Bundle the DOM-free ESM core + template engine into a single UMD file the
// HTML can load with a classic <script src> tag (works from file://, no
// build tooling).
//
//   node scripts/build-core.mjs
//
// The ESM sources remain the single source of truth; this script only strips
// import/export syntax and concatenates in dependency order. Core files share
// one flat scope (they reference each other's helpers); the template engine
// gets its own block because its local `esc` collides with the core's.
// The output is generated — do not edit src/core/ladder-core.js by hand.
//
// Node consumers keep importing the .mjs files directly; the UMD file also
// sets module.exports so it can be require()d / vm-loaded for parity tests.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const coreDir = join(here, '..', 'src', 'core');
const tplDir = join(here, '..', 'src', 'templates');

const strip = (src) => src
  .replace(/^\/\/.*$/gm, '') // comments reference the ESM layout; drop them
  .replace(/import\s[\s\S]*?from\s*'[^']*';/g, '')
  .replace(/^export\s+/gm, '');

// Flat core: leaves first, shared scope.
const CORE_FILES = ['text.mjs', 'modules.mjs', 'derive.mjs', 'assets.js', 'render.mjs'];
let body = '';
for (const file of CORE_FILES) {
  body += `\n  // ---- src/core/${file} ----\n` + strip(readFileSync(join(coreDir, file), 'utf8'));
}

// Template engine: own block (local name collisions with the core), captured out.
const TPL_API = ['textRuns', 'orderedLists', 'findRun', 'renderTemplate', 'resolveParams'];
const tplSrc = strip(readFileSync(join(tplDir, 'render.mjs'), 'utf8'));
const tplCaptures = TPL_API.map((n) => `  __api__.${n} = ${n};`).join('\n');
body += `
  // ---- src/templates/render.mjs ----
  const __api__ = {};
  {
${tplSrc.split('\n').map((l) => (l.trim() ? '  ' + l : l)).join('\n')}
${tplCaptures}
  }
`;

// Extraction rules for the browser (pdf.js text layer -> same ruleset as the
// CLI; stitch + rules are dependency-free). Own blocks: local names collide
// with the core (`norm` etc.).
const EXTRACT_FILES = [
  { file: join(coreDir, '..', 'extract', 'stitch.mjs'), api: ['stitchText'] },
  { file: join(coreDir, '..', 'extract', 'rules.mjs'), api: ['extractRules'] },
];
for (const { file, api } of EXTRACT_FILES) {
  const src = strip(readFileSync(file, 'utf8'));
  const captures = api.map((n) => `  __api__.${n} = ${n};`).join('\n');
  body += `
  // ---- ${file.split('/').slice(-2).join('/')} ----
  {
${src.split('\n').map((l) => (l.trim() ? '  ' + l : l)).join('\n')}
${captures}
  }
`;
}

const out = `// Generated by scripts/build-core.mjs — do not edit by hand.
// UMD bundle of src/core/*.mjs + src/templates/render.mjs (single source of
// truth). Rebuild: npm run build.
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.LadderCore = factory();
}(typeof self !== 'undefined' ? self : globalThis, function () {
  'use strict';
${body}
  return Object.assign(__api__, {
    // core
    esc, num, fmt, text, line, dimensionX, dimensionY, commonDefs, isoDate,
    MODULES, DEFAULTS, RANGES, MODULE_FIELDS, paramsFor, rangeError,
    overall, cageModel, CAGE_APPROVAL_IMG, CAGE_LOGO_IMG,
    renderCat, renderTrolley, renderCage, renderSVG, renderDocument,
  });
}));
`;

const dest = join(coreDir, 'ladder-core.js');
writeFileSync(dest, out);
console.log(`wrote ${dest} (${(out.length / 1024).toFixed(1)} KB)`);
