#!/usr/bin/env node
// Bundle the DOM-free ESM core into a single UMD file the HTML can load
// with a classic <script src> tag (works from file://, no build tooling).
//
//   node scripts/build-core.mjs
//
// The ESM sources under src/core/ remain the single source of truth; this
// script only strips import/export syntax and concatenates in dependency
// order. The output is generated — do not edit src/core/ladder-core.js by hand.
//
// Node consumers keep importing the .mjs files directly; the UMD file also
// sets module.exports so it can be require()d for parity tests.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const coreDir = join(here, '..', 'src', 'core');

// Dependency order: leaves first.
const FILES = ['text.mjs', 'modules.mjs', 'derive.mjs', 'assets.js', 'render.mjs'];

const PUBLIC_API = [
  // modules.mjs
  'MODULES', 'DEFAULTS', 'RANGES', 'MODULE_FIELDS', 'paramsFor', 'rangeError',
  // derive.mjs
  'overall', 'cageModel',
  // text.mjs
  'esc', 'num', 'fmt', 'text', 'line', 'dimensionX', 'dimensionY', 'commonDefs', 'isoDate',
  // assets.js
  'CAGE_APPROVAL_IMG', 'CAGE_LOGO_IMG',
  // render.mjs
  'renderCat', 'renderTrolley', 'renderCage', 'renderSVG', 'renderDocument',
];

let body = '';
for (const file of FILES) {
  let src = readFileSync(join(coreDir, file), 'utf8');
  src = src
    .replace(/^\/\/.*$/gm, '') // comments reference the ESM layout; drop them
    .replace(/import\s[\s\S]*?from\s*'[^']*';/g, '')
    .replace(/^export\s+/gm, '');
  body += `\n  // ---- ${file} ----\n` + src;
}

const out = `// Generated by scripts/build-core.mjs — do not edit by hand.
// UMD bundle of src/core/*.mjs (single source of truth). Rebuild: npm run build.
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.LadderCore = factory();
}(typeof self !== 'undefined' ? self : globalThis, function () {
  'use strict';
${body}
  return { ${PUBLIC_API.join(', ')} };
}));
`;

const dest = join(coreDir, 'ladder-core.js');
writeFileSync(dest, out);
console.log(`wrote ${dest} (${(out.length / 1024).toFixed(1)} KB)`);
